-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity frodo_unpack_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    C_address1 : OUT STD_LOGIC_VECTOR (5 downto 0);
    C_ce1 : OUT STD_LOGIC;
    C_we1 : OUT STD_LOGIC;
    C_d1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    b_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    b_ce0 : OUT STD_LOGIC;
    b_q0 : IN STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of frodo_unpack_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv14_12C0 : STD_LOGIC_VECTOR (13 downto 0) := "01001011000000";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv31_7FFFFFFF : STD_LOGIC_VECTOR (30 downto 0) := "1111111111111111111111111111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv31_F : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000001111";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal val_0_reg_130 : STD_LOGIC_VECTOR (15 downto 0);
    signal l_0_reg_143 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_170_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_347 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal shl_ln_fu_180_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal shl_ln_reg_352 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln7_fu_164_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_0_cast_fu_188_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal j_0_cast_reg_357 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln8_fu_192_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal j_fu_198_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_reg_366 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln11_fu_204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln11_reg_371 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state4_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal l_fu_210_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal bIdx_0_load_reg_380 : STD_LOGIC_VECTOR (31 downto 0);
    signal val_fu_255_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state4 : STD_LOGIC;
    signal i_0_reg_108 : STD_LOGIC_VECTOR (3 downto 0);
    signal j_0_reg_119 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln15_fu_229_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln21_fu_325_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal bIdx_0_fu_70 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln16_1_fu_304_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_sig_allocacmp_bIdx_0_load : STD_LOGIC_VECTOR (31 downto 0);
    signal BBit_0_fu_74 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln16_fu_300_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln21_fu_176_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln15_fu_219_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln15_fu_223_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln15_fu_237_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal lshr_ln15_fu_241_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal trunc_ln15_5_fu_251_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal trunc_ln15_4_fu_247_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln16_fu_263_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal BBit_fu_267_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_fu_279_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln16_3_fu_273_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal select_ln16_fu_292_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal bIdx_fu_287_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln21_fu_321_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((icmp_ln8_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state4) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state4);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif (((icmp_ln8_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    BBit_0_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_reg_371 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                                BBit_0_fu_74(30 downto 0) <= zext_ln16_fu_300_p1(30 downto 0);
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                BBit_0_fu_74(0) <= '1';
                BBit_0_fu_74(1) <= '1';
                BBit_0_fu_74(2) <= '1';
                BBit_0_fu_74(3) <= '1';
                BBit_0_fu_74(4) <= '0';
                BBit_0_fu_74(5) <= '0';
                BBit_0_fu_74(6) <= '0';
                BBit_0_fu_74(7) <= '0';
                BBit_0_fu_74(8) <= '0';
                BBit_0_fu_74(9) <= '0';
                BBit_0_fu_74(10) <= '0';
                BBit_0_fu_74(11) <= '0';
                BBit_0_fu_74(12) <= '0';
                BBit_0_fu_74(13) <= '0';
                BBit_0_fu_74(14) <= '0';
                BBit_0_fu_74(15) <= '0';
                BBit_0_fu_74(16) <= '0';
                BBit_0_fu_74(17) <= '0';
                BBit_0_fu_74(18) <= '0';
                BBit_0_fu_74(19) <= '0';
                BBit_0_fu_74(20) <= '0';
                BBit_0_fu_74(21) <= '0';
                BBit_0_fu_74(22) <= '0';
                BBit_0_fu_74(23) <= '0';
                BBit_0_fu_74(24) <= '0';
                BBit_0_fu_74(25) <= '0';
                BBit_0_fu_74(26) <= '0';
                BBit_0_fu_74(27) <= '0';
                BBit_0_fu_74(28) <= '0';
                BBit_0_fu_74(29) <= '0';
                BBit_0_fu_74(30) <= '0';
            end if; 
        end if;
    end process;

    bIdx_0_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_reg_371 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                bIdx_0_fu_70 <= select_ln16_1_fu_304_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                bIdx_0_fu_70 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_0_reg_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln8_fu_192_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_0_reg_108 <= i_reg_347;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_108 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    j_0_reg_119_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln7_fu_164_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                j_0_reg_119 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                j_0_reg_119 <= j_reg_366;
            end if; 
        end if;
    end process;

    l_0_reg_143_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_fu_204_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                l_0_reg_143 <= l_fu_210_p2;
            elsif (((icmp_ln8_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                l_0_reg_143 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    val_0_reg_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_reg_371 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                val_0_reg_130 <= val_fu_255_p3;
            elsif (((icmp_ln8_fu_192_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                val_0_reg_130 <= ap_const_lv16_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln11_fu_204_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                bIdx_0_load_reg_380 <= ap_sig_allocacmp_bIdx_0_load;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_reg_347 <= i_fu_170_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                icmp_ln11_reg_371 <= icmp_ln11_fu_204_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    j_0_cast_reg_357(3 downto 0) <= j_0_cast_fu_188_p1(3 downto 0);
                j_reg_366 <= j_fu_198_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln7_fu_164_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    shl_ln_reg_352(5 downto 3) <= shl_ln_fu_180_p3(5 downto 3);
            end if;
        end if;
    end process;
    shl_ln_reg_352(2 downto 0) <= "000";
    j_0_cast_reg_357(5 downto 4) <= "00";
    BBit_0_fu_74(31) <= '0';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln7_fu_164_p2, ap_CS_fsm_state3, icmp_ln8_fu_192_p2, icmp_ln11_fu_204_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln7_fu_164_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln8_fu_192_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((icmp_ln11_fu_204_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((icmp_ln11_fu_204_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    BBit_fu_267_p2 <= std_logic_vector(signed(ap_const_lv32_FFFFFFFF) + signed(BBit_0_fu_74));
    C_address1 <= zext_ln21_fu_325_p1(6 - 1 downto 0);

    C_ce1_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            C_ce1 <= ap_const_logic_1;
        else 
            C_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    C_d1 <= val_0_reg_130;

    C_we1_assign_proc : process(ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            C_we1 <= ap_const_logic_1;
        else 
            C_we1 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln15_fu_223_p2 <= std_logic_vector(unsigned(ap_const_lv14_12C0) + unsigned(trunc_ln15_fu_219_p1));
    add_ln16_3_fu_273_p2 <= std_logic_vector(signed(ap_const_lv31_7FFFFFFF) + signed(trunc_ln16_fu_263_p1));
    add_ln21_fu_321_p2 <= std_logic_vector(unsigned(shl_ln_reg_352) + unsigned(j_0_cast_reg_357));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state4_assign_proc : process(icmp_ln11_fu_204_p2)
    begin
        if ((icmp_ln11_fu_204_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state4 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln7_fu_164_p2)
    begin
        if ((((icmp_ln7_fu_164_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln7_fu_164_p2)
    begin
        if (((icmp_ln7_fu_164_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_bIdx_0_load_assign_proc : process(icmp_ln11_reg_371, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, bIdx_0_fu_70, select_ln16_1_fu_304_p3)
    begin
        if (((icmp_ln11_reg_371 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_bIdx_0_load <= select_ln16_1_fu_304_p3;
        else 
            ap_sig_allocacmp_bIdx_0_load <= bIdx_0_fu_70;
        end if; 
    end process;

    bIdx_fu_287_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(bIdx_0_load_reg_380));
    b_address0 <= sext_ln15_fu_229_p1(13 - 1 downto 0);

    b_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            b_ce0 <= ap_const_logic_1;
        else 
            b_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_170_p2 <= std_logic_vector(unsigned(i_0_reg_108) + unsigned(ap_const_lv4_1));
    icmp_ln11_fu_204_p2 <= "1" when (l_0_reg_143 = ap_const_lv4_F) else "0";
    icmp_ln7_fu_164_p2 <= "1" when (i_0_reg_108 = ap_const_lv4_8) else "0";
    icmp_ln8_fu_192_p2 <= "1" when (j_0_reg_119 = ap_const_lv4_8) else "0";
    j_0_cast_fu_188_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(j_0_reg_119),6));
    j_fu_198_p2 <= std_logic_vector(unsigned(j_0_reg_119) + unsigned(ap_const_lv4_1));
    l_fu_210_p2 <= std_logic_vector(unsigned(l_0_reg_143) + unsigned(ap_const_lv4_1));
    lshr_ln15_fu_241_p2 <= std_logic_vector(shift_right(unsigned(zext_ln15_fu_237_p1),to_integer(unsigned('0' & BBit_0_fu_74(31-1 downto 0)))));
    select_ln16_1_fu_304_p3 <= 
        bIdx_fu_287_p2 when (tmp_3_fu_279_p3(0) = '1') else 
        bIdx_0_load_reg_380;
    select_ln16_fu_292_p3 <= 
        ap_const_lv31_F when (tmp_3_fu_279_p3(0) = '1') else 
        add_ln16_3_fu_273_p2;
        sext_ln15_fu_229_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln15_fu_223_p2),64));

    shl_ln_fu_180_p3 <= (trunc_ln21_fu_176_p1 & ap_const_lv3_0);
    tmp_3_fu_279_p3 <= BBit_fu_267_p2(31 downto 31);
    trunc_ln15_4_fu_247_p1 <= lshr_ln15_fu_241_p2(1 - 1 downto 0);
    trunc_ln15_5_fu_251_p1 <= val_0_reg_130(15 - 1 downto 0);
    trunc_ln15_fu_219_p1 <= ap_sig_allocacmp_bIdx_0_load(14 - 1 downto 0);
    trunc_ln16_fu_263_p1 <= BBit_0_fu_74(31 - 1 downto 0);
    trunc_ln21_fu_176_p1 <= i_0_reg_108(3 - 1 downto 0);
    val_fu_255_p3 <= (trunc_ln15_5_fu_251_p1 & trunc_ln15_4_fu_247_p1);
    zext_ln15_fu_237_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(b_q0),32));
    zext_ln16_fu_300_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln16_fu_292_p3),32));
    zext_ln21_fu_325_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln21_fu_321_p2),64));
end behav;
